repos:
  # General pre-commit hooks
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v5.0.0
    hooks:
      - id: trailing-whitespace
        name: Remove trailing whitespace
        description: Trims whitespace from the end of lines
      - id: end-of-file-fixer
        name: Fix end of files
        description: Ensures files end with a newline
      - id: check-yaml
        name: Check YAML syntax
        description: Validates YAML file syntax
      - id: check-json
        name: Check JSON syntax
        description: Validates JSON file syntax
      - id: check-toml
        name: Check TOML syntax
        description: Validates TOML file syntax
      - id: check-added-large-files
        name: Check for large files
        description: Prevents adding files larger than 500kB
      - id: check-merge-conflict
        name: Check for merge conflicts
        description: Detects merge conflict markers
      - id: check-case-conflict
        name: Check for case conflicts
        description: Detects files with names that differ only in case
      - id: check-docstring-first
        name: Check docstring is first
        description: Ensures docstring comes before code in Python files
      - id: debug-statements
        name: Check for debug statements
        description: Detects debug statements like pdb imports
      - id: mixed-line-ending
        name: Fix mixed line endings
        description: Ensures consistent line endings (LF)
        args: [--fix=lf]
      - id: requirements-txt-fixer
        name: Fix requirements.txt order
        description: Ensures requirements.txt is sorted and formatted correctly

  # Import sorting with isort
  - repo: https://github.com/pycqa/isort
    rev: 6.0.1
    hooks:
      - id: isort
        name: Sort Python imports
        description: Automatically sorts and organizes Python imports
        args: [--profile=black, --multi-line=3, --line-length=88]

  # Python code formatting with black
  - repo: https://github.com/psf/black
    rev: 25.1.0
    hooks:
      - id: black
        name: Format Python code with Black
        description: Automatically formats Python code to consistent style
        language_version: python3
        args: [--line-length=88]

  # Remove unused imports and variables with autoflake
  - repo: https://github.com/PyCQA/autoflake
    rev: v2.3.1
    hooks:
      - id: autoflake
        name: Remove unused imports and variables
        description: Automatically removes unused imports and variables from Python code
        args:
          [
            --expand-star-imports,
            --remove-all-unused-imports,
            --remove-unused-variables,
            --ignore-init-module-imports,
            --ignore-pass-after-docstring,
            --in-place,
          ]

# Global settings
default_stages: [pre-commit]
fail_fast: false
